/*
 * This file was generated by the Gradle 'init' task - and mofified afterwards
 *
 * This file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import dev.jbang.gradle.tasks.JBangTask

plugins {
    `java-library`
    id("dev.jbang") version "0.3.0-SNAPSHOT"
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    api(libs.commons.math3)
    implementation(libs.guava)
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter("5.12.1")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


tasks.register<JBangTask>("helloworld") {
    group = "demo"

    script = rootProject.layout.projectDirectory.file("jbang/helloworld").asFile.absolutePath
}
